# Generated by Django 4.0.3 on 2023-06-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='client',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_personnel',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
